1. Solucion de capitulos completos y AWK 2. Depuracion de codigo redundante 3. Parical 2 SO

diff --git a/LOSCAPITULOS/CAP11/remb b/LOSCAPITULOS/CAP11/remb
--- a/LOSCAPITULOS/CAP11/remb
+++ b/LOSCAPITULOS/CAP11/remb
@@ -1,34 +1,22 @@
-#
-#
-# Remove someone from the phone book
-#
-if [ "$#" -ne 1 ]
-then
-    echo "Incorrect number of arguments"
-    echo "Usage: remb name"
-    exit 1
+# Remueve a alguien del directorio
+
+if [ "$#" -ne 1 ]; then
+  echo "Incorrect number of arguments"
+  echo "Usage: remb name"
+  exit 1
 fi
 
 name=$1
 
-#
-#Find number of matching entries
-#
+# Encuentra el numero de coincidencias
+matches=$(grep "$name" $PHONEBOOK | wc -l)
 
-matches=`grep "$name"  $PHONEBOOK | wc -l `
-
-#
-# If more than one match, issue message, else remove it
-#
-if [ "$matches" -gt 1 ]
-then
-   echo "More than one match; please qualify futher"
-elif [ "$matches" -eq 1 ]
-then 
-    grep -v "$name"  $PHONEBOOK > /tmp/phonebook$$
-    mv /tmp/phonebook$$ $PHONEBOOK
+# Si hay mas de una coincidencia, muestra mensaje, si no, lo elimina
+if [ "$matches" -gt 1 ]; then
+  echo "More than one match; please qualify futher"
+elif [ "$matches" -eq 1 ]; then
+  grep -v "$name" $PHONEBOOK >/tmp/phonebook$$
+  mv /tmp/phonebook$$ $PHONEBOOK
 else
-   echo "I couldn't find $name in phone book"
-fi   
-sed  "/$1/d" phonebook > tmp/phonebook
-mv tmp/phonebook phonebook
+  echo "I couldn't find $name in phone book"
+fi
diff --git a/LOSCAPITULOS/CAP14/remb b/LOSCAPITULOS/CAP14/remb
--- a/LOSCAPITULOS/CAP14/remb
+++ b/LOSCAPITULOS/CAP14/remb
@@ -8,37 +8,32 @@ name=$1
 #
 #Find number of matching entries
 # and save in temp file
-grep "$name"  $PHONEBOOK  > temp/matches$$
+grep "$name" $PHONEBOOK >temp/matches$$
 
-if [ ! -s temp/matches$$ ]
-then
-   echo " I can't find $name in the phone book"
-   exit 1
+if [ ! -s temp/matches$$ ]; then
+  echo " I can't find $name in the phone book"
+  exit 1
 fi
 #
 # Display mayching entries one at a time and confirm removal
 #
-while read line
-do
-    display "$line"
-    echo -n "Remove this entry (y/n)? "
-    read answer < /dev/tty
+while read line; do
+  display "$line"
+  echo -n "Remove this entry (y/n)? "
+  read answer </dev/tty
 
-    if [ "$answer" = y ]
-    then
-        break
-    fi
-done < temp/matches$$
+  if [ "$answer" = y ]; then
+    break
+  fi
+done <temp/matches$$
 
 rm temp/matches$$
 
-if [ "$answer" = y ]
-then
-     if grep -v "^$line$"  $PHONEBOOK > temp/phonebook$$
-     then
-        mv temp/phonebook$$ $PHONEBOOK
-        echo -n "Selected entry has been removed"
-     else
-         echo "I couldn't find $name in phone book"
-     fi   
+if [ "$answer" = y ]; then
+  if grep -v "^$line$" $PHONEBOOK >temp/phonebook$$; then
+    mv temp/phonebook$$ $PHONEBOOK
+    echo -n "Selected entry has been removed"
+  else
+    echo "I couldn't find $name in phone book"
+  fi
 fi
